"""
fred_account_simulator.py
----------------------------
Simulates what would ACTUALLY have happened to a real trading account,
given the trades in fred_historical_trades.csv -- not just "what was the
win rate per trade" (which fred_historical_check.py already reports),
but "what happens when two signals overlap and only 2 concurrent slots
exist, so one of them never actually gets taken."

This is the gap between "a signal fired" and "a trade was actually
possible" -- a pair's signal can look great in isolation but never
materialize if your account was already full when it fired.

═══════════════════════════════════════════════════════════════════════
REQUIRES A CSV WITH BOTH entry_timestamp AND exit_timestamp COLUMNS
═══════════════════════════════════════════════════════════════════════
If your CSV only has a single "timestamp" column (no exit_timestamp),
it was generated by an older version of fred_historical_check.py --
re-run that script to regenerate the CSV with both columns before using
this simulator. Without a real exit time, there is no way to know
whether a trade was still occupying an account slot when a later signal
fired, which is the entire point of this tool.

RULES ENFORCED, MATCHING THE LIVE SYSTEM'S config.py EXACTLY
(change the constants below if your real config.py settings differ):
  - STARTING_CAPITAL: starting account balance
  - RISK_PERCENT_PER_TRADE: % of CURRENT balance risked per trade
    (compounding -- each trade's risk is based on the balance AT THAT
    MOMENT, not the original starting capital)
  - MAX_CONCURRENT_TRADES: hard cap on simultaneously open trades,
    across ALL pairs combined (matches validate_alert()'s real check)
  - PAIR_GRADE_FILTERS: a signal that fails this is never even
    considered a candidate (matches validate_alert() exactly)
  - CONDITIONAL_TIERS: these (strategy, session) combos only get taken
    if the account is COMPLETELY FLAT (0 open positions) at that exact
    moment -- otherwise skipped, matching the live conditional-tier rule

HOW CONCURRENCY IS DECIDED: all trades are sorted by entry_timestamp and
processed in that exact chronological order -- the same order they'd
actually have arrived at your webhook in real life. Before considering
each trade, any currently-open position whose exit_timestamp has
already passed is freed up first. If no slot is free (or a conditional
tier's flat-account requirement isn't met), that signal is SKIPPED
entirely -- it never affects the account, it's simply as if it had
never fired.

TRADES STILL "OPEN" AT THE END OF THE DATA WINDOW: these have no real
exit_timestamp (the data ran out before they resolved). They're treated
as occupying their slot for the rest of the simulation once opened --
the conservative assumption, since there's no way to know when they'd
actually have closed.
"""

import csv
import sys
from datetime import datetime

STARTING_CAPITAL = 100.0
RISK_PERCENT_PER_TRADE = 10.0
MAX_CONCURRENT_TRADES = 2
PAIR_GRADE_FILTERS = {"ETHUSDT": {"A+", "A"}}
CONDITIONAL_TIERS = {
    ("Momentum Continuation", "US"),
    ("Mean Reversion", "Europe"),
}

CSV_INPUT_FILE = "fred_historical_trades.csv"
EQUITY_CURVE_OUTPUT_FILE = "fred_equity_curve.csv"


def load_trades(filename):
    with open(filename) as f:
        rows = list(csv.DictReader(f))

    if "exit_timestamp" not in rows[0] if rows else {}:
        print(f"ERROR: {filename} has no 'exit_timestamp' column -- it was generated by an")
        print(f"older version of fred_historical_check.py. Re-run that script to regenerate")
        print(f"the CSV with both entry_timestamp and exit_timestamp before using this tool.")
        sys.exit(1)

    for r in rows:
        r["entry_dt"] = datetime.strptime(r["entry_timestamp"], "%Y-%m-%d %H:%M")
        r["exit_dt"] = (datetime.strptime(r["exit_timestamp"], "%Y-%m-%d %H:%M")
                         if r["exit_timestamp"] else None)  # None = still OPEN at end of data
        r["r_multiple"] = float(r["r_multiple"])

    rows.sort(key=lambda r: r["entry_dt"])
    return rows


def passes_grade_filter(trade):
    symbol = trade["symbol"]
    if symbol in PAIR_GRADE_FILTERS:
        return trade["grade"] in PAIR_GRADE_FILTERS[symbol]
    return True


def is_conditional_tier(trade):
    return (trade["strategy"], trade["session"]) in CONDITIONAL_TIERS


def run_simulation(trades):
    balance = STARTING_CAPITAL
    peak_balance = STARTING_CAPITAL
    max_drawdown_pct = 0.0

    open_positions = []  # list of exit_dt (None = open indefinitely) for currently-occupied slots
    equity_curve = []    # (timestamp, balance, event_description)
    taken = 0
    skipped_grade_filter = 0
    skipped_no_slot = 0
    skipped_conditional = 0

    for trade in trades:
        # Free up any positions that have genuinely closed by now
        open_positions = [exit_dt for exit_dt in open_positions
                           if exit_dt is None or exit_dt > trade["entry_dt"]]

        if not passes_grade_filter(trade):
            skipped_grade_filter += 1
            continue

        if is_conditional_tier(trade) and len(open_positions) > 0:
            skipped_conditional += 1
            continue

        if len(open_positions) >= MAX_CONCURRENT_TRADES:
            skipped_no_slot += 1
            continue

        # Trade is actually taken -- compute compounding position size
        risk_amount = balance * (RISK_PERCENT_PER_TRADE / 100)
        profit_or_loss = risk_amount * trade["r_multiple"]
        balance += profit_or_loss
        taken += 1

        open_positions.append(trade["exit_dt"])

        peak_balance = max(peak_balance, balance)
        drawdown_pct = ((peak_balance - balance) / peak_balance * 100) if peak_balance > 0 else 0
        max_drawdown_pct = max(max_drawdown_pct, drawdown_pct)

        equity_curve.append({
            "timestamp": trade["entry_timestamp"],
            "symbol": trade["symbol"],
            "strategy": trade["strategy"],
            "outcome": trade["outcome"],
            "risk_amount": round(risk_amount, 2),
            "profit_loss": round(profit_or_loss, 2),
            "balance": round(balance, 2),
        })

    return {
        "final_balance": balance,
        "peak_balance": peak_balance,
        "max_drawdown_pct": max_drawdown_pct,
        "taken": taken,
        "skipped_grade_filter": skipped_grade_filter,
        "skipped_no_slot": skipped_no_slot,
        "skipped_conditional": skipped_conditional,
        "equity_curve": equity_curve,
    }


def export_equity_curve(equity_curve, filename=EQUITY_CURVE_OUTPUT_FILE):
    if not equity_curve:
        print(f"\nNo trades were taken -- {filename} not created.")
        return
    fieldnames = ["timestamp", "symbol", "strategy", "outcome", "risk_amount", "profit_loss", "balance"]
    with open(filename, "w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        for row in equity_curve:
            writer.writerow(row)
    print(f"Exported {len(equity_curve)}-trade equity curve to {filename}")
    print(f"Import into Google Sheets the same way as before, then chart the 'balance' column")
    print(f"over time for a visual equity curve.")


def main():
    input_file = sys.argv[1] if len(sys.argv) > 1 else CSV_INPUT_FILE
    print(f"Loading trades from {input_file}...")
    trades = load_trades(input_file)
    print(f"Loaded {len(trades)} total signals (across all pairs/models), sorted chronologically.\n")

    result = run_simulation(trades)

    print("=" * 70)
    print("ACCOUNT SIMULATION RESULT")
    print("=" * 70)
    print(f"Starting capital:      ${STARTING_CAPITAL:,.2f}")
    print(f"Ending balance:        ${result['final_balance']:,.2f}")
    total_return_pct = (result['final_balance'] - STARTING_CAPITAL) / STARTING_CAPITAL * 100
    print(f"Total return:          {total_return_pct:+.1f}%")
    print(f"Peak balance reached:  ${result['peak_balance']:,.2f}")
    print(f"Max drawdown:          {result['max_drawdown_pct']:.1f}%  (worst dip from a peak, along the way)")
    print()
    print(f"Signals that fired:    {len(trades)}")
    print(f"  Actually taken:      {result['taken']}")
    print(f"  Skipped (ETH grade filter):        {result['skipped_grade_filter']}")
    print(f"  Skipped (no free slot, 2 already open): {result['skipped_no_slot']}")
    print(f"  Skipped (conditional tier, account not flat): {result['skipped_conditional']}")
    print("=" * 70)

    export_equity_curve(result["equity_curve"])


if __name__ == "__main__":
    main()
